### PR TITLE
Use FarmHash128 instead of SHA1

### PR DESCRIPTION
**Pull request by boblangley**
Uses this implementation of FarmHash128: https://github.com/TommasoBelluzzo/FastHashes

https://github.com/google/farmhash

Some things I am not 💯 sure about.

- It requires `unsafe` compilation.
- I disabled checking for architecture, assuming all of our customers would run on `x86` or `amd64` hardware.

### CODE REVIEW

**Comment by danielmarbach** [comment]
Unsafe compilation has no effect on consumers of the lib so we should be safe. I do think if we are considering pulling this in we should stick to the original implementation as much as possible because the author intentionally put the platform check there.

My question is more if we have trust enough in pulling the implementation in. Based on the history it seems https://www.nuget.org/packages/Farmhash.Sharp/ has more acceptance in the community but unfortunately that one doesn't provide the 128-bit version we require to have enough bytes to turn them into a GUID

**Comment by danielmarbach** [comment]
image

**Comment by danielmarbach** [comment]
Found also https://www.nuget.org/packages/System.Data.HashFunction.FarmHash/ and run the benchmark against it

image

**Comment by danielmarbach** [comment]
I'm coming more and more to the conclusion that it is probably not worth the risk of having collisions just to improve the speed. We need unique id's for the saga document id so maybe staying with SHA1 is a good approach

**Comment by danielmarbach** [comment]
Reusing also doesn't seem to work https://medium.com/@wanderingdeveloper/c-cautionary-tail-the-dangers-of-sha256-reuse-2b5bb9c6fde9

**Comment by boblangley** [comment]
Good enough for me.

**Pull request closed without merging**
