### PR TITLE
Resolve CosmosClient from the container when instructed to do so

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Let's discuss this PR in the sync today.

**Comment by SeanFeldman** [comment]
Do you mean https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/32 replaces this one? Specifically, [`1c79569` (#32)](https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/32/commits/1c79569d79e2f54ded558bd8418ab336b9ebca8d#diff-dd8cd4d033a5b4c57392324089dfbab0R11).

**Comment by SeanFeldman** [comment]
An alternative approach using a provider was discussed. A replacement PR will be opened later today.

**Comment by boblangley** [comment]
Replaced by #33

**Pull request closed without merging**
