### PR TITLE
Subscriptions implementation

### PR DESCRIPTION
**Pull request by SeanFeldman**
An attempt to add subscription persistence support to CosmosDB Core API.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Tests currently fail.
I've tried to go with the `Should_add_endpoint_on_new_subscription` first. It fails at querying.
I have a feeling that the document structure should be different\* rather than storying each subscription as a document but haven't tried it.

\* for example, storing a message type as a document and all endpoints with their addresses as arrays of pairs under it.

``` json
{
  "id": "messagetype1",
  "subscribers": [
    { "endpoint":"endpoint1", "transportAddress": "address1" },
    { "endpoint":"endpoint2", "transportAddress": "address2" }
  ],
}
```

**Comment by andreasohlund** [comment]
>for example, storing a message type as a document and all endpoints with their addresses as arrays of pairs under it.

That's what RavenDB do so I think that would work.

@ramonsmits and @timbussmann decided against that for mongodb tho?

**Comment by timbussmann** [comment]
the community persisters used this approach as well. After talking to RavenDB persistence experts and our own research, we went with a 1 subscription = 1 document approach, although MongoDB brings some useful future for nested arrays in documents like set based update operations and special indexes. However, our current approach feels a bit simpler while can still serve all the results completely from indexes.

**Comment by ramonsmits** [comment]
We based our design on https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1 which gives guidance on one-to-many models for document storages making a distinction between:
- One-to-Few
- One-to-Many
- One-to-Squillions

Based on that guidance we think subscriptions would fall under One-to-Many which uses a document per subscription. Unfortunately, the guidance doesn't give a soft limit at to how many 'a few' is.

**Comment by danielmarbach** [comment]
Closing for now since this is not in scope for the preview. The good ideas and proposals here are not lost

**Pull request closed without merging**
